### PR TITLE
Zoom guidelines

### PR DESCRIPTION
**Pull request by jmertic**

### CODE REVIEW

**Comment by bobdahlberg** [comment]
Looks good

**Comment by jmertic** [comment]
---------- Forwarded message ---------
From: Peter Fandel <pfandel@rocketsoftware.com>
Date: Fri, Apr 17, 2020 at 10:01 AM
Subject: Re: [Open Mainframe Project TAC Private] VOTE: Zoom Guidelines
To: omp-tac-private@lists.openmainframeproject.org <
omp-tac-private@lists.openmainframeproject.org>


+1

**Comment by jmertic** [comment]
---------- Forwarded message ---------
From: James Caffrey <caffreyj@us.ibm.com>
Date: Fri, Apr 17, 2020 at 10:32 AM
Subject: Re: [Open Mainframe Project TAC Private] VOTE: Zoom Guidelines
To: <omp-tac-private@lists.openmainframeproject.org>


Approve
_._,_._,_

**Comment by jmertic** [comment]
---------- Forwarded message ---------
From: Tully, Phil (CORP) via lists.openmainframeproject.org <Phil.Tully=
adp.com@lists.openmainframeproject.org>
Date: Fri, Apr 17, 2020 at 10:38 AM
Subject: Re: [Open Mainframe Project TAC Private] VOTE: Zoom Guidelines
To: omp-tac-private@lists.openmainframeproject.org <
omp-tac-private@lists.openmainframeproject.org>


Approve



Regards, Phil Tully

Chief Architect-z/VM & z/Linux
_._,_._,_

**Comment by jmertic** [comment]
---------- Forwarded message ---------
From: Enyu Wang <enyuw@ca.ibm.com>
Date: Fri, Apr 17, 2020 at 11:01 AM
Subject: Re: [Open Mainframe Project TAC Private] VOTE: Zoom Guidelines
To: <omp-tac-private@lists.openmainframeproject.org>
Cc: <omp-tac-private@lists.openmainframeproject.org>


Approve.
_._,_._,_

**Comment by jmertic** [comment]
Approved - merging

**Pull request merged**
