### PR TITLE
Add agenda item to discuss renewal criteria for Intubation projects a…

### PR DESCRIPTION
**Pull request by jmertic**
…nd criteria for considering Emeritus status

Requested by @hogstrom 

Signed-off-by: John Mertic <jmertic@linuxfoundation.org>

### CODE REVIEW

**Comment by jmertic** [comment]
@hogstrom Can you confirm this captures what you are proposing?

**Comment by jmertic** [comment]
Matt - since you can't make today's meeting should we move to next month's meeting?

**Comment by hogstrom** [comment]
Yes please, thanks John.

Matt Hogstrom
matt@hogstrom.org
+1-919-656-0564
PGP Key: 0x90ECB270
Facebook <https://facebook.com/matt.hogstrom>  LinkedIn <https://linkedin/in/mhogstrom>  Twitter <https://twitter.com/hogstrom>

“It may be cognitive, but, it ain’t intuitive."
— Hogstrom

**Comment by jmertic** [comment]
Great! Closing this as I've added it to the agenda.

**Pull request closed without merging**
